vtes_website_index:
    path: /
    defaults: { _controller: VtesWebsiteBundle:Default:index }

vtes_website_players:
    resource: "@VtesWebsiteBundle/Resources/config/routing/players.yml"
    prefix: /players

vtes_website_user:
    resource: "@VtesWebsiteBundle/Resources/config/routing/user.yml"
    prefix:   /user
