services:
  vtes_website.locale_listener:
    class: Vtes\Bundle\WebsiteBundle\EventListener\LocaleListener
    arguments: ["%kernel.default_locale%"]
    tags:
      - { name: kernel.event_subscriber }
